import { Head, Link, router } from "@inertiajs/react";
import { useState } from "react";
import { ArrowLeft, Edit, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { destroy, edit, index } from "@/routes/units";
export default function UnitShow({ unit }: { unit: { id: number; unit_number: string; unit_type: string; property: { name: string }; floor: string | null; bedrooms: number; bathrooms: number; monthly_rent: string; status: string; notes: string | null } }) { const [confirming, setConfirming] = useState(false); return <><Head title={`Unit ${unit.unit_number} — SOMFIX`} /><div className="w-full p-4 md:p-6"><div className="flex flex-wrap items-start justify-between gap-4 border-b pb-5"><div><div className="flex gap-2"><h1 className="text-2xl font-bold">Unit {unit.unit_number}</h1><Badge variant="outline">{unit.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{unit.property.name} · {unit.unit_type}</p></div><div className="flex gap-2"><Button asChild size="sm" variant="outline"><Link href={edit(unit.id)}><Edit />Edit</Link></Button>{confirming ? <Button size="sm" variant="destructive" onClick={() => router.delete(destroy.url(unit.id))}>Confirm delete</Button> : <Button size="sm" variant="outline" onClick={() => setConfirming(true)}><Trash2 />Delete</Button>}<Button asChild size="sm" variant="outline"><Link href={index()}><ArrowLeft />Back</Link></Button></div></div><div className="mt-6 grid gap-4 rounded-2xl border bg-card p-5 sm:grid-cols-3"><Detail label="Floor" value={unit.floor ?? "—"} /><Detail label="Bedrooms" value={String(unit.bedrooms)} /><Detail label="Bathrooms" value={String(unit.bathrooms)} /><Detail label="Monthly rent" value={`$${Number(unit.monthly_rent).toLocaleString()}`} /><div className="sm:col-span-3"><Detail label="Notes" value={unit.notes ?? "No notes added."} /></div></div></div></>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
UnitShow.layout = { breadcrumbs: [{ title: "Units", href: index() }, { title: "Unit details", href: index() }] };
